// 200+ Maharashtra Engineering Colleges Mock Data
// Categories: Top 50 (High Cutoff), Medium 100 (Avg Cutoff), Low 50 (Low Cutoff)

const topColleges = [
  { name: 'COEP Pune', rank: 120 },
  { name: 'VJTI Mumbai', rank: 150 },
  { name: 'SPIT Mumbai', rank: 300 },
  { name: 'PICT Pune', rank: 450 },
  { name: 'Walchand Sangli', rank: 600 },
  { name: 'VIT Pune', rank: 900 },
  { name: 'D.J. Sanghvi Mumbai', rank: 1100 },
  { name: 'PCCOE Pune', rank: 1500 },
  { name: 'Thadomal Shahani Mumbai', rank: 1800 },
  { name: 'Cummins College (Women) Pune', rank: 2000 },
  { name: 'V.E.S.I.T. Mumbai', rank: 2500 },
  { name: 'K.J. Somaiya Mumbai', rank: 2800 },
  { name: 'MIT WPU Pune', rank: 3200 },
  { name: 'DY Patil Akurdi', rank: 3800 },
  { name: 'Fr. C. Rodrigues Bandra', rank: 4100 },
  { name: 'RCOEM Nagpur', rank: 4500 },
  { name: 'Vishwakarma Institute of Technology', rank: 4800 },
  { name: 'Government College of Engineering Aurangabad', rank: 5000 },
  { name: 'Government College of Engineering Amravati', rank: 5500 },
  { name: 'Sardar Patel College of Engineering', rank: 6000 },
  { name: 'Army Institute of Technology', rank: 6500 },
  { name: 'Pimpri Chinchwad College of Engineering & Research', rank: 7000 },
  { name: 'Ramrao Adik Institute of Technology', rank: 7500 },
  { name: 'Dwarkadas J. Sanghvi College of Engineering', rank: 8000 },
  { name: 'Vivekanand Education Society', rank: 8500 },
  { name: 'St. Francis Institute of Technology', rank: 9000 },
  { name: 'Vidyalankar Institute of Technology', rank: 9500 },
  { name: 'Don Bosco Institute of Technology', rank: 10000 },
  { name: 'SIES Graduate School of Technology', rank: 10500 },
  { name: 'Xavier Institute of Engineering', rank: 11000 },
  { name: 'Atharva College of Engineering', rank: 11500 },
  { name: 'Rajiv Gandhi Institute of Technology', rank: 12000 },
  { name: 'M.H. Saboo Siddik College of Engineering', rank: 12500 },
  { name: 'Datta Meghe College of Engineering', rank: 13000 },
  { name: 'Lokmanya Tilak College of Engineering', rank: 13500 },
  { name: 'Terna Engineering College', rank: 14000 },
  { name: 'Pillai College of Engineering', rank: 14500 },
  { name: 'MGM College of Engineering', rank: 15000 },
  { name: 'Bharti Vidyapeeth College of Engineering', rank: 15500 },
  { name: 'Sinhgad College of Engineering', rank: 16000 },
  { name: 'Zeal College of Engineering', rank: 16500 },
  { name: 'JSPM Narhe Technical Campus', rank: 17000 },
  { name: 'Trinity College of Engineering', rank: 17500 },
  { name: 'NBN Sinhgad School of Engineering', rank: 18000 },
  { name: 'Smt. Kashibai Navale College of Engineering', rank: 18500 },
  { name: 'Marathwada Mitra Mandal College of Engineering', rank: 19000 },
  { name: 'Modern Education Society College of Engineering', rank: 19500 },
  { name: 'All India Shri Shivaji Memorial Society', rank: 20000 },
  { name: 'Progressive Education Society', rank: 20500 },
  { name: 'Genba Sopanrao Moze College of Engineering', rank: 21000 }
];

const mediumColleges = [
  { name: 'DY Patil Pimpri', rank: 22000 },
  { name: 'Indira College of Engineering', rank: 23000 },
  { name: 'Jayawantrao Sawant College of Engineering', rank: 24000 },
  { name: 'Keystone School of Engineering', rank: 25000 },
  { name: 'Nuttan Maharashtra Institute of Engineering', rank: 26000 },
  { name: 'PK Technical Campus', rank: 27000 },
  { name: 'Pune Vidhyarthi Griha', rank: 28000 },
  { name: 'Rajgad Dnyanpeeth', rank: 29000 },
  { name: 'Sahyadri Valley College', rank: 30000 },
  { name: 'Siddhant College of Engineering', rank: 31000 },
  { name: 'Someshwar Engineering College', rank: 32000 },
  { name: 'Suman Ramesh Tulsiani', rank: 33000 },
  { name: 'Universal College of Engineering', rank: 34000 },
  { name: 'Vidya Pratishthan', rank: 35000 },
  { name: 'Vishwakarma Institute of Information Technology', rank: 36000 },
  { name: 'Waghire College', rank: 37000 },
  { name: 'Yashwantrao Chavan College', rank: 38000 },
  { name: 'ZES Dnyanganga', rank: 39000 },
  { name: 'Abhinav Education Society', rank: 40000 },
  { name: 'Adhyapak Shikshan Mandal', rank: 41000 },
  { name: 'Adsul Technical Campus', rank: 42000 },
  { name: 'Al-Ameen Educational', rank: 43000 },
  { name: 'Amrutvahini College', rank: 44000 },
  { name: 'Anantrao Pawar College', rank: 45000 },
  { name: 'Annasaheb Dange', rank: 46000 },
  { name: 'Ashokrao Mane Group', rank: 47000 },
  { name: 'Bajaj Institute of Technology', rank: 48000 },
  { name: 'Bhivarabai Sawant', rank: 49000 },
  { name: 'Bramhadevdada Mane', rank: 50000 },
  { name: 'Chhatrapati Shahu', rank: 51000 },
  { name: 'Dattajirao Kadam', rank: 52000 },
  { name: 'Deogiri Institute', rank: 53000 },
  { name: 'Dhole Patil College', rank: 54000 },
  { name: 'Dr. D.Y. Patil School of Engineering', rank: 55000 },
  { name: 'Fabtech Technical Campus', rank: 56000 },
  { name: 'G.H. Raisoni Ahmednagar', rank: 57000 },
  { name: 'G.H. Raisoni Jalgaon', rank: 58000 },
  { name: 'G.H. Raisoni Pune', rank: 59000 },
  { name: 'Gudage Institute', rank: 60000 },
  { name: 'Guru Gobind Singhji', rank: 61000 },
  { name: 'Hi-Tech Institute', rank: 62000 },
  { name: 'Hon. Shri. Babanrao Pachpute', rank: 63000 },
  { name: 'International Institute of Information Technology', rank: 64000 },
  { name: 'J.T. Mahajan', rank: 65000 },
  { name: 'Jawaharlal Nehru Engineering', rank: 66000 },
  { name: 'K.C.E. Society', rank: 67000 },
  { name: 'K.K. Wagh', rank: 68000 },
  { name: 'Kalyani Charitable Trust', rank: 69000 },
  { name: 'Karmaveer Bhaurao Patil', rank: 70000 },
  { name: 'Kavikulguru Institute', rank: 71000 },
  { name: 'KJEI Trinity', rank: 72000 },
  { name: 'Konkan Gyanpeeth', rank: 73000 },
  { name: 'Late G.N. Sapkal', rank: 74000 },
  { name: 'Lokmangal Science', rank: 75000 },
  { name: 'MAEER\'s MIT', rank: 76000 },
  { name: 'Mahavir Education Society', rank: 77000 },
  { name: 'Matoshri College', rank: 78000 },
  { name: 'MET Institute', rank: 79000 },
  { name: 'MGM\'s Jawaharlal Nehru', rank: 80000 },
  { name: 'Modern Education Society', rank: 81000 },
  { name: 'N.B. Navale', rank: 82000 },
  { name: 'Nagar Yuwak Shikshan', rank: 83000 },
  { name: 'Nashik District Maratha', rank: 84000 },
  { name: 'Navsahyadri Education', rank: 85000 },
  { name: 'Padmabhooshan Vasantra', rank: 86000 },
  { name: 'Padmashri Dr. V.B. Kolte', rank: 87000 },
  { name: 'Parvatibai Genba', rank: 88000 },
  { name: 'Pimpri Chinchwad Education', rank: 89000 },
  { name: 'Pravara Rural', rank: 90000 },
  { name: 'Prof. Ram Meghe', rank: 91000 },
  { name: 'R.C. Patel', rank: 92000 },
  { name: 'Rajendra Mane', rank: 93000 },
  { name: 'Sandip Foundation', rank: 94000 },
  { name: 'Sanjivan Engineering', rank: 95000 },
  { name: 'Sanmati Engineering', rank: 96000 },
  { name: 'Sant Gadge Baba', rank: 97000 },
  { name: 'Saraswati Education', rank: 98000 },
  { name: 'Shah and Anchor', rank: 99000 },
  { name: 'Shram Sadhana', rank: 100000 },
  { name: 'Shree L.R. Tiwari', rank: 101000 },
  { name: 'Shree Ramchandra', rank: 102000 },
  { name: 'Shri Gulabrao Deokar', rank: 103000 },
  { name: 'Shri Ramdeobaba', rank: 104000 },
  { name: 'Shri Sant Gajanan', rank: 105000 },
  { name: 'Shri Shivaji Education', rank: 106000 },
  { name: 'Shri Vithal Education', rank: 107000 },
  { name: 'Sinhgad Academy', rank: 108000 },
  { name: 'Sinhgad Institute of Technology', rank: 109000 },
  { name: 'Sinhgad Technical Education', rank: 110000 },
  { name: 'Sipna Shikshan', rank: 111000 },
  { name: 'Sir Visvesvaraya', rank: 112000 },
  { name: 'Smt. Indira Gandhi', rank: 113000 },
  { name: 'Smt. Radhikatai Pandav', rank: 114000 },
  { name: 'Sneha-Vsrdik', rank: 115000 },
  { name: 'Sou. Sushila Danchand', rank: 116000 },
  { name: 'SSPM\'s College', rank: 117000 },
  { name: 'St. John College', rank: 118000 },
  { name: 'St. Vincent Pallotti', rank: 119000 },
  { name: 'Suryodaya College', rank: 120000 },
  { name: 'Sveris College', rank: 121000 }
];

const lowColleges = [
  { name: 'Tatyasaheb Kore', rank: 125000 },
  { name: 'Terna Public', rank: 126000 },
  { name: 'Theem College', rank: 127000 },
  { name: 'Tulsiramji Gaikwad', rank: 128000 },
  { name: 'Usha Mittal', rank: 129000 },
  { name: 'Vasantdada Patil', rank: 130000 },
  { name: 'Vidya Vardhini', rank: 131000 },
  { name: 'Vilasrao Deshmukh', rank: 132000 },
  { name: 'Vishwabharati', rank: 133000 },
  { name: 'Vishwatmak Om Gururadev', rank: 134000 },
  { name: 'Wainganga College', rank: 135000 },
  { name: 'Walchand Institute', rank: 136000 },
  { name: 'Watumull Institute', rank: 137000 },
  { name: 'Yadavrao Tasgaonkar', rank: 138000 },
  { name: 'Yashoda Technical', rank: 139000 },
  { name: 'Yashwantrao Bhonsale', rank: 140000 },
  { name: 'Dattakala Group', rank: 141000 },
  { name: 'Dilkap Research', rank: 142000 },
  { name: 'Dr. A.D. Shinde', rank: 143000 },
  { name: 'Dr. J.J. Magdum', rank: 144000 },
  { name: 'Dr. Rajendra Gode', rank: 145000 },
  { name: 'Dr. Sau. Kamaltai', rank: 146000 },
  { name: 'Flora Institute', rank: 147000 },
  { name: 'G.M. Vedak', rank: 148000 },
  { name: 'Gharda Foundation', rank: 149000 },
  { name: 'Godavari Foundation', rank: 150000 },
  { name: 'Gramin Technical', rank: 151000 },
  { name: 'Ideal Institute', rank: 152000 },
  { name: 'Jagadambha Bahuuddeshiya', rank: 153000 },
  { name: 'K.D. Gavit', rank: 154000 },
  { name: 'K.J. College', rank: 155000 },
  { name: 'K.V.N. Naik', rank: 156000 },
  { name: 'Late Narayandas Bhawandas', rank: 157000 },
  { name: 'Mauli Group', rank: 158000 },
  { name: 'Met\'s Institute', rank: 159000 },
  { name: 'Mitra Sadhana', rank: 160000 },
  { name: 'Nandurbar Taluka', rank: 161000 },
  { name: 'Nashik Gramin', rank: 162000 },
  { name: 'Navneet Bhai', rank: 163000 },
  { name: 'Nisarg Sevabhavi', rank: 164000 },
  { name: 'Om Engineering', rank: 165000 },
  { name: 'P.R. Pote', rank: 166000 },
  { name: 'Pad. Dr. V.B. Kolte', rank: 167000 },
  { name: 'Pradnya Niketan', rank: 168000 },
  { name: 'Priyadarshini', rank: 169000 },
  { name: 'Radha Govind', rank: 170000 },
  { name: 'Raje Ramrao', rank: 171000 },
  { name: 'Rajiv Gandhi', rank: 172000 },
  { name: 'Samarth Group', rank: 173000 },
  { name: 'Saraswati Danwantri', rank: 174000 }
];

// Combine and add metadata
let allColleges = [];
let id = 1;

const addColleges = (list, type) => {
  list.forEach(c => {
    // Computer Engineering (Standard)
    allColleges.push({
      id: id++,
      name: c.name,
      branch: 'Computer',
      category: 'OPEN',
      closingRank: c.rank,
      round: 'CAP-1',
      type
    });
    // OBC Variant (slightly higher rank allowed)
    allColleges.push({
      id: id++,
      name: c.name,
      branch: 'Computer',
      category: 'OBC',
      closingRank: c.rank + 1500,
      round: 'CAP-1',
      type
    });
    // IT Branch (Lower cutoff than CS)
    allColleges.push({
      id: id++,
      name: c.name,
      branch: 'IT',
      category: 'OPEN',
      closingRank: c.rank + 800,
      round: 'CAP-1',
      type
    });
  });
}

addColleges(topColleges, 'Top');
addColleges(mediumColleges, 'Medium');
addColleges(lowColleges, 'Low');

export const colleges = allColleges;

// Export FAQs (Unchanged)
export const chatbotFAQs = [
  { question: 'What is CAP?', answer: 'CAP (Centralized Admission Process) is the official admission process.' },
  { question: 'Which colleges can I get?', answer: 'Check the Prediction section based on your rank.' },
  { question: 'What documents are required?', answer: 'See the Documents section for a checklist.' },
  { question: 'What is TFWS?', answer: 'Tuition Fee Waiver Scheme for economically weaker students.' },
  { question: 'What is the last date?', answer: 'See the CAP Tracker for dates.' }
];
